"""Physics parameter-sweep shorts, rendered in Blender instead of generated by a model.

The format: one scene, one number swept, the value burned into the frame - "1kg / 10kg /
50kg", "Soft 0% / 25% / 50%". Nothing about it is invented, so nothing about it needs a
video model; it is a simulation run several times.

    blender_runner   locate Blender, run a scene script headless, sweep a parameter
    scenes/          one module per scene template, each a standalone bpy script

Blender is driven HEADLESS (`blender -b -P script.py`), not through the MCP add-on: the
add-on needs a visible session and a human in the loop, which a job queue does not have.
"""

from .blender_runner import (      # noqa: F401
    BlenderNotFound,
    SweepResult,
    blender_path,
    render_sweep,
    run_scene,
)

__all__ = ["blender_path", "run_scene", "render_sweep", "SweepResult", "BlenderNotFound"]
