"""Material sound for a physics sweep.

Two things you hear, both generated by `physics_mode.make_material_sounds`:

  IMPACT    one heavy hit on the frame the solver actually made contact. The scene writes
            that frame to impacts.json; guessing it from the clip length puts the thud
            before or after the picture and the illusion dies immediately.
  DEBRIS    blocks tumbling and settling, starting just after the impact.

A swing swell sits under the approach at low level.

There is deliberately NO continuous background bed. The earlier version laid filtered
noise under the whole video to keep the gaps from feeling empty; what it actually did was
put an audible hiss over everything. Silence between hits is better than noise, and the
debris tail covers most of the gap anyway.

Levels follow the swept value: a 50kg hit is louder and longer than a 1kg one, which is
the whole point of the format.
"""

from __future__ import annotations

import json
import subprocess
from dataclasses import dataclass, field
from pathlib import Path
from typing import Sequence

# Generated material sounds first, by exact filename; the fragments are a fallback for
# anyone dropping their own files into the library.
LAYERS = {
    "impact": ("impact_heavy", "impact", "thud", "boom"),
    "debris": ("debris_wood", "debris", "rubble", "gravel", "crumble"),
    "swing": ("swing_air", "whoosh", "swipe", "swoosh"),
}

# assets/physics_sound is generated and holds the modal material sounds. soundeffects is
# the app's meme/editing library - searched last, and only as a fallback, because a Wii
# boom on a collapsing brick tower sounds like an edit rather than an impact.
DEFAULT_ROOTS = ("assets/physics_sound", "soundeffects")


def _library(roots) -> list[Path]:
    if isinstance(roots, (str, Path)):
        roots = [roots]
    files: list[Path] = []
    for r in roots:
        root = Path(r)
        if root.exists():
            files += [p for p in root.rglob("*")
                      if p.suffix.lower() in (".mp3", ".wav", ".ogg", ".m4a", ".flac")]
    return files


def pick(kind: str, roots=DEFAULT_ROOTS) -> str | None:
    """First library file whose name carries one of the fragments for `kind`."""
    files = _library(roots)
    for frag in LAYERS.get(kind, ()):
        for p in files:
            if frag in p.name.lower():
                return str(p)
    return None


@dataclass
class SoundEvent:
    path: str
    start: float
    gain: float
    kind: str

    def as_dict(self) -> dict:
        return {"path": self.path, "start": round(self.start, 3),
                "gain": round(self.gain, 3), "kind": self.kind}


@dataclass
class SoundPlan:
    events: list[SoundEvent] = field(default_factory=list)

    def as_dict(self) -> dict:
        return {"events": [e.as_dict() for e in self.events]}


def plan_for_sweep(sweep: Sequence[dict], library=DEFAULT_ROOTS,
                   *, clip_seconds: float | None = None) -> SoundPlan:
    """Build the sound plan from the sweep's impacts.json files.

    `sweep` rows come from blender_runner (label, value, frames_dir). Each row's
    impacts.json carries the contact frame and fps, so every hit lands on the frame the
    picture shows it.
    """
    plan = SoundPlan()
    imp = pick("impact", library)
    deb = pick("debris", library)
    swi = pick("swing", library)
    values = [float(r.get("value") or 0) for r in sweep] or [1.0]
    vmax = max(values) or 1.0
    offset = 0.0
    for row in sweep:
        d = Path(row.get("frames_dir", ""))
        meta = {}
        f = d / "impacts.json"
        if f.exists():
            try:
                meta = json.loads(f.read_text("utf-8"))
            except Exception:  # noqa: BLE001
                meta = {}
        fps = float(meta.get("fps") or 30)
        contact = meta.get("contact_frame")
        seconds = float(row.get("seconds_len") or clip_seconds or 0.0)
        if not seconds:
            n = len(list(d.glob("frame_*.png")))
            seconds = n / fps if n else 4.0
        hit = (float(contact) / fps) if contact else seconds * 0.45
        # louder with the swept value - a 50kg hit must not sound like 1kg
        v = float(row.get("value") or 0)
        loud = 0.45 + 0.55 * (v / vmax) ** 0.5
        # Levels pulled back deliberately. Impacts at near-full scale are exciting once and
        # tiring on the third loop; this format is watched over and over, so the hit has to
        # land without ever feeling like it is shouting.
        if swi:
            plan.events.append(SoundEvent(swi, offset + max(0.0, hit - 0.55),
                                          0.16 * loud, "swing"))
        if imp:
            plan.events.append(SoundEvent(imp, offset + hit, min(0.8, 0.66 * loud),
                                          "impact"))
        if deb:
            # 0.12s after contact: the first bricks are already moving inside the impact
            # sound itself, this is the rest of the tower arriving on the floor.
            plan.events.append(SoundEvent(deb, offset + hit + 0.12,
                                          min(0.6, 0.4 * loud), "debris"))
        offset += seconds
    return plan


def plan_for_loop(frames_dir, repeats: int, loop_seconds: float,
                  library=DEFAULT_ROOTS) -> SoundPlan:
    """One sound per landing, repeated for every pass of the loop.

    The scene lists every landing frame and whether it was a gap or solid tile, so the
    sound follows the picture instead of a fixed metronome - and because the events are
    generated per repeat at exactly `loop_seconds` apart, the audio loops with the video.
    """
    plan = SoundPlan()
    f = Path(frames_dir) / "impacts.json"
    if not f.exists():
        return plan
    try:
        meta = json.loads(f.read_text("utf-8"))
    except Exception:  # noqa: BLE001
        return plan
    fps = float(meta.get("fps") or 30)
    imp = pick("impact", library)
    deb = pick("debris", library)
    for r in range(max(1, int(repeats))):
        base = r * loop_seconds
        for ev in meta.get("events", []):
            t = base + float(ev.get("frame", 0)) / fps
            hole = ev.get("kind") == "hole"
            strength = float(ev.get("strength") or 0.6)
            if imp:
                plan.events.append(SoundEvent(imp, t, min(1.0, 0.34 * strength), "land"))
            # only a gap gets the settle tail - every landing rattling would smear the
            # rhythm that makes the loop hypnotic in the first place
            if hole and deb:
                plan.events.append(SoundEvent(deb, t + 0.05, 0.16 * strength, "settle"))
    return plan


def plan_for_events(frames_dir, offset: float = 0.0,
                    library=DEFAULT_ROOTS) -> SoundPlan:
    """Place a sound on every event a scene declared in its impacts.json.

    Used for authored scenes, where the app does not know in advance what happens - the
    scene names its own moments and this puts a material sound on each of them.
    """
    plan = SoundPlan()
    f = Path(frames_dir) / "impacts.json"
    if not f.exists():
        return plan
    try:
        meta = json.loads(f.read_text("utf-8"))
    except Exception:  # noqa: BLE001
        return plan
    fps = float(meta.get("fps") or 30)
    imp = pick("impact", library)
    deb = pick("debris", library)
    for ev in meta.get("events", []):
        t = offset + float(ev.get("frame", 0)) / fps
        strength = min(1.0, max(0.05, float(ev.get("strength") or 0.6)))
        if imp:
            plan.events.append(SoundEvent(imp, t, min(1.0, 0.8 * strength), "impact"))
        # a heavy event gets a settle tail; light taps stay dry so the rhythm reads
        if deb and strength >= 0.7:
            plan.events.append(SoundEvent(deb, t + 0.12, 0.5 * strength, "debris"))
    return plan


def mux(video: str | Path, plan: SoundPlan, out_path: str | Path,
        ffmpeg: str = "ffmpeg", duration: float | None = None) -> str | None:
    """Mix the plan onto the video. Returns the output path, or None if nothing mixed."""
    video, out_path = Path(video), Path(out_path)
    if not video.exists() or not plan.events:
        return None
    inputs, filters, labels = ["-i", str(video)], [], []
    for i, ev in enumerate(plan.events):
        inputs += ["-i", ev.path]
        delay = int(round(ev.start * 1000))
        filters.append(f"[{i + 1}:a]adelay={delay}:all=1,volume={ev.gain:.3f}[e{i}]")
        labels.append(f"[e{i}]")
    # duration=LONGEST, and then padded/trimmed to the video. With the background bed gone
    # the first amix input became a 0.7s swing sound, so `duration=first` made the mixed
    # track 0.7s long and `-shortest` then cut the VIDEO down to 19 frames - a 12 second
    # render delivered as two thirds of a second.
    dur = float(duration or 0)
    tail = f",apad,atrim=0:{dur:.3f}" if dur else ""
    mix = (f"{''.join(labels)}amix=inputs={len(labels)}:duration=longest:"
           f"dropout_transition=0:normalize=0{tail}")
    # No compressor. With a background bed it was needed to lift the quiet parts; with
    # nothing between the hits it would only pump the silence up and down.
    measured = _measure_loudness(inputs, filters, mix, ffmpeg)
    norm = "loudnorm=I=-16:TP=-1.5:LRA=11"
    if measured:
        norm += (f":measured_I={measured['input_i']}:measured_TP={measured['input_tp']}"
                 f":measured_LRA={measured['input_lra']}"
                 f":measured_thresh={measured['input_thresh']}"
                 f":offset={measured['target_offset']}:linear=true")
    # Limiter AFTER loudnorm: in front of it, loudnorm's own output still overshot to
    # +0.4 dBTP once AAC encoding added its usual overshoot on top.
    filters.append(f"{mix},{norm},alimiter=limit=0.85:level=disabled[aout]")
    cmd = [ffmpeg, "-y", "-hide_banner", "-loglevel", "error"] + inputs + [
        "-filter_complex", ";".join(filters), "-map", "0:v", "-map", "[aout]",
        "-c:v", "copy", "-c:a", "aac", "-b:a", "192k", "-ar", "48000",
        "-movflags", "+faststart", str(out_path)]
    r = subprocess.run(cmd, capture_output=True, text=True, timeout=1800)
    return str(out_path) if out_path.exists() and r.returncode == 0 else None


def _measure_loudness(inputs, filters, mix, ffmpeg) -> dict | None:
    """Analysis pass of a two-pass loudnorm. None if ffmpeg printed nothing usable."""
    cmd = [ffmpeg, "-hide_banner"] + inputs + [
        "-filter_complex", ";".join(filters
                                    + [f"{mix},loudnorm=I=-16:TP=-1.5:LRA=11:"
                                       "print_format=json[aout]"]),
        "-map", "[aout]", "-f", "null", "-"]
    try:
        r = subprocess.run(cmd, capture_output=True, text=True, timeout=1800)
    except subprocess.SubprocessError:
        return None
    text = (r.stderr or "") + (r.stdout or "")
    start, end = text.rfind("{"), text.rfind("}")
    if start < 0 or end < start:
        return None
    try:
        data = json.loads(text[start:end + 1])
        return {k: data[k] for k in ("input_i", "input_tp", "input_lra",
                                     "input_thresh", "target_offset")}
    except (ValueError, KeyError):
        return None
